### ISSUE TITLE
useHeightAdjustment to use container scroll state rather than WindowContext

### ISSUE THREAD

**Issue by thefat32** [siriwatknp/mui-treasury#504] opened 2020-02-24 22:27 UTC
Hi there, our web app has a custom main loader which defined height needs to be fixed to 100vh, our app's main container is a direct child of the loader. This can't be changed due to loader functionality. So scroll function is handled by the container. Therefore the window object in WindowContext has no change in the scroll state breaking "Header Magnet" feature. It would be great if we could pass a ref to the container where the layout is placed so the scroll state could be fetched from it.

Would this be possible? Is there any workaround for this. Please if you need an example or any further explanation ask me. English is not my native languge so my writting can result confusing sometimes.

Greetings and thanks for this awesome lib

**Comment by siriwatknp** [comment] 2020-03-07 11:52
If you could provide an example I can reproduce, that would be very helpful.

**Comment by siriwatknp** [comment] 2020-07-21 15:58
I will close this issue since it is not used in v4.

**Closed by siriwatknp** 2020-07-21 15:58 UTC
